//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ProductCategories = new HashSet<ProductCategory>();
            this.Childs = new HashSet<Category>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public int CreatedUserId { get; set; }
    
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<Category> Childs { get; set; }
        public virtual Category Parent { get; set; }
        public virtual User User { get; set; }
    }
}
