//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderId { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ShippingTelephone { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> LocationCityId { get; set; }
        public Nullable<int> LocationDistrictId { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Location LocationCity { get; set; }
        public virtual Location LocationDistrict { get; set; }
    }
}
