//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
            this.Orders = new HashSet<Order>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Email { get; set; }
        public string RealName { get; set; }
        public Nullable<int> LocationDistrictId { get; set; }
        public Nullable<int> LocationCityId { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
